# Generated by Django 4.2.3 on 2023-07-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangovideo',
            name='video',
            field=models.FileField(upload_to='static/django_videos'),
        ),
        migrations.AlterField(
            model_name='pythonvideo',
            name='video',
            field=models.FileField(upload_to='static/python_videos'),
        ),
        migrations.AlterField(
            model_name='tailwindvideo',
            name='video',
            field=models.FileField(upload_to='static/tailwind_videos'),
        ),
    ]
