# Generated by Django 4.2.3 on 2023-07-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_djangovideo_video_alter_pythonvideo_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangovideo',
            name='video',
            field=models.FileField(upload_to='core/static/django_videos'),
        ),
        migrations.AlterField(
            model_name='htmlvideo',
            name='video',
            field=models.FileField(upload_to='core/static/html_videos'),
        ),
        migrations.AlterField(
            model_name='pythonvideo',
            name='video',
            field=models.FileField(upload_to='core/static/python_videos'),
        ),
        migrations.AlterField(
            model_name='tailwindvideo',
            name='video',
            field=models.FileField(upload_to='core/static/tailwind_videos'),
        ),
    ]
