# Generated by Django 4.2.3 on 2023-07-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_djangovideo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangovideo',
            name='video',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='htmlvideo',
            name='video',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pythonvideo',
            name='video',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='tailwindvideo',
            name='video',
            field=models.URLField(),
        ),
    ]
